### PR TITLE
chore: update to chokidar 4.0.3

### LINKED ISSUE #13380: Upgrade to chokidar 4.0.3
### Describe the problem

The latest chokidar causes type-checking to fail due to https://github.com/paulmillr/chokidar/pull/1381

### Describe the proposed solution

This line will probably need to be tweaked by someone who knows TypeScript:

https://github.com/sveltejs/kit/blob/01f001bd861e399027a580c9402b7b6206de3d24/packages/package/src/index.js#L81

```
src/index.js:81:61 - error TS2345: Argument of type '(value: any) => void' is not assignable to parameter of type '() => void'.
  Target signature provides too few arguments. Expected 1 or more, but got 0.

81  const ready = new Promise((resolve) => watcher.on('ready', resolve));
```

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by rChaoz**
Closes #13380

Not sure if I should add a changeset for this, I thought it's better not to?

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [ ] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by benmccann** [comment]
thank you!
