### ISSUE TITLE
Regression(#13914): Svelte 4 does not have an export named `untrack`

### ISSUE THREAD

**Issue by yhx-12243** [sveltejs/kit#13932]
### Describe the bug

This causes the compilation error when using svelte 4 and @sveltejs/kit 2 with newest compatible version (^4 and ^2).

### Reproduction

Any project with following `package.json` will causes a compilation error.
```json
"devDependencies": {
    "@sveltejs/kit": "^2",
    "svelte": "^4"
}
```

### Logs

```Shell
../../node_modules/.pnpm/@sveltejs+kit@2.22.1_@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.20_vite@5.4.19/node_modules/@sveltejs/kit/src/runtime/client/client.js (2:24): "untrack" is not exported by "../../node_modules/.pnpm/svelte@4.2.20/node_modules/svelte/src/runtime/ssr.js", imported by "../../node_modules/.pnpm/@sveltejs+kit@2.22.1_@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.20_vite@5.4.19/node_modules/@sveltejs/kit/src/runtime/client/client.js".
```

### System Info

```Shell
Any
```

### Severity

annoyance

**Comment by Ocean-OS** [comment]
I must've forgotten to tag this in #13933, could someone please close this?

**Comment by yhx-12243** [comment]
Resolved by #13933.

**Comment by cmjoseph07** [comment]
@Ocean-OS @yhx-12243 

This was did not resolve the build issue when I build with 2.22.2 instead of 2.21.4. 

```
node_modules/@sveltejs/kit/src/runtime/client/client.js (4:23): "untrack" is not exported by "node_modules/svelte/src/runtime/index.js", imported by "node_modules/@sveltejs/kit/src/runtime/client/client.js".
```
