### ISSUE TITLE
Netlify problem with v175

### ISSUE THREAD

**Issue by bekos** [sveltejs/kit#2559]
### Describe the bug

After upgrading to v175 I started having issues with Netlify deployment, with `Cannot find module 'stream/package.json'`

### Reproduction

I will provide one repro if requested.

### Logs

![image](https://user-images.githubusercontent.com/551595/136162547-2a241054-cae6-46d8-ac35-9017680aa4a8.png)

### System Info

```shell
This happens only Netlify.
```

### Severity

blocking an upgrade

**Comment by dominikg** [comment]
duplicate of #2523
