### ISSUE TITLE
Upgrade to TypeScript 4.4

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2322]
### Describe the problem

We're on TypeScript 4.3

### Describe the proposed solution

Upgrade to 4.4

### Importance

nice to have

**Comment by Theo-Steiner** [comment]
@benmccann you may already know this, but for now rollup builds get stuck with typescript 4.4 or greater, making this milestone dependant on this upstream issue: [rollup/plugins#983](https://github.com/rollup/plugins/issues/983)

**Comment by benmccann** [comment]
Thanks. I wasn't aware, but expect we won't face that issue because we don't use `@rollup/plugin-typescript`

**Comment by Conduitry** [comment]
Vite does. I don't know whether it's just part of its own build process or whether the shipped package ends up containing a bundled copy of it.

**Comment by benmccann** [comment]
I still imagine it shouldn't matter for us. We don't ship the TypeScript library. It will just enable slightly stricter type checking on our own code when we run `pnpm check`. And I don't think Vite would run `@rollup/plugin-typescript` on our code because we haven't added that to our plugin config

**Comment by vhfmag** [comment]
I've just tried to work on this issue and [I think I got it to work](https://github.com/vhfmag/kit/compare/vhfmag:master...vhfmag:fix/2322), but I'm not sure what path to take around handling a breaking change:

After upgrading, all the new TypeScript compilation errors were caused by the [new `useUnknownInCatchVariables` flag](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables), automatically enabled in the project because of the `strict` flag. To work around the issue, there are a couple paths:

1. Disable the `useUnknownInCatchVariables` flag in `tsconfig.json`
2. Explicitly type all catch bindings (e.g. `catch (/** @type {any} */ error)` or `catch (/** @type {Error} */ error)`)
3. Type check the catch binding in runtime

[My solution so far](https://github.com/vhfmag/kit/compare/vhfmag:master...vhfmag:fix/2322) took path 3, creating a utility `assertError` function that throws if its argument isn't `instanceof Error`, so that after calling it, the variable's type is safely narrowed to `Error`. I thought I'd ask if it's desirable or if I should change course before opening a PR.

**Comment by benmccann** [comment]
That sounds reasonable to me. @ignatiusmb @dummdidumm are more of TypeScript experts than I am though

**Comment by benmccann** [comment]
Btw, we also have a `coalesce_to_error` function that's used some places. We should probably remove the typecast to `unknown` before that function is called when we upgrade to 4.4

**Comment by dummdidumm** [comment]
Sounds reasonable to me, but we need to be careful that these are all `instanceof Error`. For example `getRawBody` of `node/index.js` `reject`s and I'm not 100% sure if the rejected value is a instance/subclass of `Error` (but I would hope so).

**Comment by bluwy** [comment]
I think it's also worth noting that `Error` might not actually be the nodejs error we want, but the browser error instead, which lacks some extra properties. [More info](https://dev.to/jdbar/the-problem-with-handling-node-js-errors-in-typescript-and-the-workaround-m64). I also encountered this issue for vite-plugin-svelte and it's really tangled for what seem to be simple. I'd be interested to see how the checks are implemented here as well.

> Explicitly type all catch bindings (e.g. `catch (/** @type {any} */ error)` or `catch (/** @type {Error} */ error)`)

I tried this as well but in a typescript file, and typescript actually explicitly prevents this pattern (throws error), e.g. `catch (error: any)`. It could be a different story for jsdoc.

**Comment by vhfmag** [comment]
>> Explicitly type all catch bindings (e.g. `catch (/** @type {any} */ error)` or `catch (/** @type {Error} */ error)`)
>
> I tried this as well but in a typescript file, and typescript actually explicitly prevents this pattern (throws error), e.g. `catch (error: any)`. It could be a different story for jsdoc.

You're correct, catch bindings can only be typed as `any` or `unknown`, even in JSDoc. I'll edit my original comment to clarify that.

---

> Sounds reasonable to me, but we need to be careful that these are all `instanceof Error`. For example getRawBody of `node/index.js` `reject`s and I'm not 100% sure if the rejected value is a instance/subclass of `Error` (but I would hope so).

I worried non-Error values could be thrown too, but relaxed a little after all tests ran without triggering the assertion errors. Now, investigating further, I found [one instance of throwing/rejecting a non-Error value](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/node/index.js#L27-L30) and two catch bindings expecting its shape ([1](https://github.com/sveltejs/kit/blob/0c07dd8a21fe86234216cd02770b8aaf8b7d4854/packages/kit/src/core/dev/index.js#L334-L335), [2](https://github.com/sveltejs/kit/blob/0c07dd8a21fe86234216cd02770b8aaf8b7d4854/packages/kit/src/core/preview/index.js#L82-L83)). Maybe I should create a `HttpError` class with `status` and `reason` fields to be thrown in place of the plain object, and type check it with `assertInstanceOf(error, HttpError)`?

Otherwise, is there some additional way to test if it's safe to implement the checks as `instanceof Error`? 

---

> I think it's also worth noting that Error might not actually be the nodejs error we want, but the browser error instead, which lacks some extra properties. [More info](https://dev.to/jdbar/the-problem-with-handling-node-js-errors-in-typescript-and-the-workaround-m64).

As is recommended by the linked article, I made sure `assertError` makes `error` type to be inferred as `Error & NodeJS.ErrnoException`. Since all the extra properties are optional, I don't think additional checks are needed. How does it sound?

**Comment by dummdidumm** [comment]
> I worried non-Error values could be thrown too, but relaxed a little after all tests ran without triggering the assertion errors. Now, investigating further, I found [one instance of throwing/rejecting a non-Error value](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/node/index.js#L27-L30) and two catch bindings expecting its shape ([1](https://github.com/sveltejs/kit/blob/0c07dd8a21fe86234216cd02770b8aaf8b7d4854/packages/kit/src/core/dev/index.js#L334-L335), [2](https://github.com/sveltejs/kit/blob/0c07dd8a21fe86234216cd02770b8aaf8b7d4854/packages/kit/src/core/preview/index.js#L82-L83)). Maybe I should create a `HttpError` class with `status` and `reason` fields to be thrown in place of the plain object, and type check it with `assertInstanceOf(error, HttpError)`?

I think the safer solution would be create such a `HttpError` as a sublcass of `Error` and leave the check as is (`instanceof Error`) so unforseen `Error`s during other code paths will still pass the assertion.

In general I'm a little hesitant to use option 3 just because such an error could by _anything_ and we can only make assumptions about its structure given the code paths we see.

> Otherwise, is there some additional way to test if it's safe to implement the checks as `instanceof Error`?

I don't think there's a good way to test this, the best way I can think of is to check the code paths that lead to these errors.

**Comment by bluwy** [comment]
> As is recommended by the linked article, I made sure `assertError` makes `error` type to be inferred as `Error & NodeJS.ErrnoException`. Since all the extra properties are optional, I don't think additional checks are needed. How does it sound?

Yeah sounds good if `NodeJS.ErrnoException` is used for the typeguard too.

Unrelated: If you do make a PR, make sure internal functions are snake_case (https://github.com/sveltejs/kit#coding-style)
