### ISSUE TITLE
Upgrade to chokidar 4.0.3

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#13380]
### Describe the problem

The latest chokidar causes type-checking to fail due to https://github.com/paulmillr/chokidar/pull/1381

### Describe the proposed solution

This line will probably need to be tweaked by someone who knows TypeScript:

https://github.com/sveltejs/kit/blob/01f001bd861e399027a580c9402b7b6206de3d24/packages/package/src/index.js#L81

```
src/index.js:81:61 - error TS2345: Argument of type '(value: any) => void' is not assignable to parameter of type '() => void'.
  Target signature provides too few arguments. Expected 1 or more, but got 0.

81  const ready = new Promise((resolve) => watcher.on('ready', resolve));
```

### Importance

nice to have

**Comment by rChaoz** [comment]
See #13381
