### ISSUE TITLE
@sveltejs/adapter-vercel v5.9.0 causes build failure

### ISSUE THREAD

**Issue by awei82** [sveltejs/kit#14232]
### Describe the bug

My sveltekit app is failing to build with the vercel adapter on version 5.9.0. (see logs below)

This error does not occur when I'm on version 5.8.2.

Suspect commit: https://github.com/sveltejs/kit/pull/13899

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-x8nj1thf
- @sveltejs/adapter-vercel pinned to 5.9.0
- svelte.config.js set to 'adapter-vercel'

run `npm run build` in terminal -> error

### Logs

```Shell
> Using @sveltejs/adapter-vercel
error during build:
TypeError: builder.hasServerInstrumentationFile is not a function
    at generate_serverless_function (file:///Users/andrewwei/crates/crates-v2/node_modules/@sveltejs/adapter-vercel/index.js:103:17)
    at adapt (file:///Users/andrewwei/crates/crates-v2/node_modules/@sveltejs/adapter-vercel/index.js:368:11)
    at adapt (file:///Users/andrewwei/crates/crates-v2/node_modules/@sveltejs/kit/src/core/adapt/index.js:38:8)
    at finalise (file:///Users/andrewwei/crates/crates-v2/node_modules/@sveltejs/kit/src/exports/vite/index.js:1074:13)
    at async Object.handler (file:///Users/andrewwei/crates/crates-v2/node_modules/@sveltejs/kit/src/exports/vite/index.js:1104:5)
    at async PluginDriver.hookParallel (file:///Users/andrewwei/crates/crates-v2/node_modules/rollup/dist/es/shared/node-entry.js:22192:17)
    at async Object.close (file:///Users/andrewwei/crates/crates-v2/node_modules/rollup/dist/es/shared/node-entry.js:23206:13)
    at async buildEnvironment (file:///Users/andrewwei/crates/crates-v2/node_modules/vite/dist/node/chunks/dep-DBxKXgDP.js:46229:17)
    at async Object.defaultBuildApp [as buildApp] (file:///Users/andrewwei/crates/crates-v2/node_modules/vite/dist/node/chunks/dep-DBxKXgDP.js:46684:5)
    at async CAC.<anonymous> (file:///Users/andrewwei/crates/crates-v2/node_modules/vite/dist/node/cli.js:863:7)
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^6.0.0 => 6.1.0 
    @sveltejs/adapter-vercel: 5.9.0 => 5.9.0 
    @sveltejs/kit: ^2.22.0 => 2.30.1 
    @sveltejs/vite-plugin-svelte: ^6.0.0 => 6.1.2 
    svelte: ^5.25.0 => 5.38.1 
    vite: ^7.0.4 => 7.1.2
```

### Severity

blocking an upgrade

**Comment by jsilveira** [comment]
I can confirm the same issue. Downgrading to "@sveltejs/adapter-vercel": "5.8.2" fixed it

**Comment by konstantinblaesi** [comment]
for me kit versions are:
- good: 2.31.0
- bad: 2.30.1 (same error as above)

check if upgrading kit to this version or newer fixes it for you as well

[looks like a fix was introduced](<https://github.com/sveltejs/kit/compare/%40sveltejs/kit%402.30.0...%40sveltejs/kit%402.31.0#diff-26328923869e101647ff12341b13c8f075331560960bb380cb892f476a052254R239>)
